## Machine Learning with Python - CognitiveClass.ai

[Course Link](https://courses.cognitiveclass.ai/courses/course-v1:BigDataUniversity+ML0101EN+2016_T3/info)

### Supervised vs Unsupervised Learning

#### ML vs Stat Modelling:

ML is an algorithm that can learn from data without being reliant on std programming practices

Stat modeling is the formulization of rel bw vars in form of mathematical eqns

It is subfield of maths

ML is subfield of CS and AI

Naming conventions:

<img src = "./data/img/diag1" height="500" width = "500" align="center">

Other diff bw ML and SM:

<img src = "./data/img/diag2" height="500" width = "500" align="center">

**Supervised and Unsupervised Learning**

In SL, we have a set of training data, or labeled data in which we know the structure and outcome of it

<img src = "./data/img/diag3" height="500" width = "500" align="center">

We take this data and train a ML model, so that it can understand patterns in the data

Once the model has been trained we can use it to predict out-of-sample data,or data in which the results are unknown

<img src = "./data/img/diag4" height="500" width = "500" align="center">

If we are given data which is unstructured, we can use USL to find patterns in that data

**SL**:

We "teach" a model, ie we load the model with knowledge so that it can predict future instances

How do we "teach" a model?

- We teach it by training it with some data from a **labeled** dataset

eg: Iris dataset

<img src = "./data/img/diag5" height="500" width = "500" align="center">

There are 2 types of SL:

1. Classification

2. Regression

**USL**:

We **do not** supervise the model, but we let the model work on its own to discover info that may not be visible to the human eye

UL uses ML algos that draw conclusions on **unlabeled data**

** Difficulties of USL vs SL **:

- USL has more difficult algos, since we know little to no info about the data, or the outcomes that are to be expected

- With USL we are trying to find things such as Groups or Clusters, Density Estimations, and Dim Redn

- USL has fewer tests and models to ensure that outcome of model is accurate
    As such, USL creates a **less controllable** env as machine is creating outcomes for us
    
- SL deals with labeled data, USL with unlabeled data
    
Eg:

<img src = "./data/img/diag6" height="500" width = "500" align="center">

Here we can see an op of an algo applied to examining poisonous mushrooms 

This is SL as its a Classification prob

Algo: Classification Tree




#### SL - Classification:

<img src = "./data/img/diag7" height="500" width = "500" align="center">

Depending on data used to train model and type of modelused, there are virtually endless possible boundaries

If we had a new out-of-sample datapoint:

<img src = "./data/img/diag8" height="500" width = "500" align="center">

The modelknows where to classify it

**KNN**:

<img src = "./data/img/diag9" height="500" width = "500" align="center">

Here k = 5

The black arrows connect the 5 nearerst pts to the unknown data pt (black cross)

Here Xu is classified as red

If k = 14:

<img src = "./data/img/diag10" height="500" width = "500" align="center">

Xu is classified as green


#### USL

USL usually deals with algos that utilize centroids.

Some of these are:

- K means Clustering
- Hierarchial Clustering
- Density based Clustering

Real world egL Classifying categories of music

**Dimensionality Reduction ** and/or **Feature Extraction** play a crucial role in this by reducing redundant features to make classification easier

USL can be used to create a Text-to-Speech program
By looking at the amp, break and freq in the sound waves the machine can estimate what word has been spoken
and convert it to text

USL can also be used for Image Processing




### Lab - ML Basics

In this lab exercise, you will learn some basic functions for viewing and analysing data such as target, feature names, etc. Also, you will get a basic understanding of how to use data to fit (train) a model and use it to make a prediction. This will serve as a building block for future labs!

### Hello! We will start by introducing you to the digits dataset.

The digits dataset is made of up of 1797 8x8 images such as the one below.
<img src = "https://ibm.box.com/shared/static/psb68kpyyt0o6kbhcq88cwj7fuv7nlhq.png">
These images are hand-written digits converted into image format. <br>
We can use this data to train our machine to further determine other 8x8 images as specific digits! <br>
Sounds like we are <i>Classifying</i> data!

First we will need to import the dataset from sklearn and declare the dataset.

In [4]:
from sklearn.datasets import load_digits

digits = load_digits()

# Now let's check out the type and data for digits. 
# The type should be 'Bunch' which is a dictionary-like object 
# specifically useful for loading sklearn internal sample datasets.

print (type(digits))

print (digits.data)

print(len(digits.data))

print (len(digits.data[0]))

<class 'sklearn.utils.Bunch'>
[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]
1797
64


1797 samples

Each: 64 features

Let's check out the description of this dataset for more information!

In [5]:
print ((digits.DESCR))

Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is a

We can see the categories that classify each of the images by invoking the target field. There is a number associated to the classification of each digit. The target field fetches these numbers, where each digit is mapped to a name in target_names

In [21]:
print (digits.target)

# Now if we print out the target_names, we can find out what the data is categorized as.

print(digits.target_names)

# An important piece of information to note is that the data is stored as a numpy datatype, 
# which is a homogeneous multidimensional array (ndarray).

print (type(digits.data))
print (type(digits.target))
print (type(digits.target_names))
print(len(digits.target))

[0 1 2 ..., 8 9 8]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1797


Now let's confirm that the shape of the data and target match (first column) 

Note: The shape of the data is a tuple, where the first field is the number of observations and the second field is the number of attributes.

In [23]:
print(digits.data.shape)

print(digits.target.shape)

(1797, 64)
(1797,)


Then we can declare variables for the data and target which will be used to fit (train) the machine!

In [24]:
X = digits.data

y = digits.target

First we need to <b>import svm</b> (an algorithm) and declare a variable called clf with gamma and C attributes.
Now we can <b>fit</b> our model and <b>predict</b> the last digit, which should be 8. <br>
<b>Note</b>: The predict function will show a warning when run. Please ignore the warning.

In [37]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)
clf.fit(X,y)

print("Predn of last element:")
print(clf.predict(digits.data)[-1])
print("Actual value of last element")
print (digits.target[-1])


Predn of last element:
8
Actual value of last element
8


### Lab - Skulls Dataset

In [38]:
from IPython.core.display import HTML
HTML("""
<style type="text/css">
    #ans:hover { background-color: black; }
    #ans {padding: 6px; 
        background-color: white; 
        border: green 2px solid; 
        font-weight: bold; }
</style>
""") 

Next, a little information about the dataset. We are using a dataset called skulls.csv, which contains the measurements made on Egyptian skulls from five epochs.

<img src = "https://ibm.box.com/shared/static/bjlklq4cwp22twi6756d2wqyn16gerh1.png", position = "center">


In the fields of chronology and periodization, an epoch is an instant in time chosen as the origin of a particular era. The "epoch" then serves as a reference point from which time is measured. Time measurement units are counted from the epoch so that the date and time of events can be specified unambiguously.

#### The attributes of the data are as follows: 

<img src = "https://ibm.box.com/shared/static/02z8krlr99hwrqa2ecx3ycuiwqkcuzjv.png", align = 'left'>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<b>epoch</b> - The epoch corresponding to each skull. Assigned as a factor with levels c4000BC c3300BC, c1850BC, c200BC, and cAD150, where the years are only given approximately.

<b>mb</b> - Maximal Breadth of the skull.

<b>bh</b> - Basiregmatic Heights of the skull.

<b>bl</b> - Basilveolar Length of the skull.

<b>nh</b> - Nasal Heights of the skull.

---

#### Import Libraries:

In [39]:
import numpy as np
import pandas
from sklearn.neighbors import KNeighborsClassifier

In [41]:
# Save the " skulls.csv " data file into a variable called my_data

my_data = pandas.read_csv('https://ibm.box.com/shared/static/u8orgfc65zmoo3i0gpt9l27un4o0cuvn.csv', delimiter=',')

print (my_data.shape)

(150, 6)


In [43]:
type(my_data)

my_data.head()

Unnamed: 0    epoch   mb   bh   bl  nh
0           1  c4000BC  131  138   89  49
1           2  c4000BC  125  131   92  48
2           3  c4000BC  131  132   99  50
3           4  c4000BC  119  132   96  44
4           5  c4000BC  136  143  100  54

When we train a model, the model requires two inputs, X and y
<ul>
    <li> X: Feature Matrix, or array that contains the data. </li>
    <li> y: Response Vector, or 1-D array that contains the classification categories </li>
</ul>

<b> Note: We will not be able to use the built-in scikit-learn functions that was used with the digits dataset, since the data is not of type bunches. </b>

------------
There are some problems with the data in my_data:
<ul>
    <li> There is a header on the data (Unnamed: 0    epoch   mb   bh   bl  nh) </li>
    <li> The data needs to be in numpy.ndarray format in order to use it in the machine learning model </li>
    <li> There is non-numeric data within the dataset </li>
    <li> There are row numbers associated with each row that affect the model </li>
</ul>

To resolve these problems, I have created a function that fixes these for us:
<b> removeColumns(pandasArray, column) </b>

This function produces one output and requires two inputs.
<ul>
    <li> 1st Input: A pandas array. The pandas array we have been using is my_data </li>
    <li> 2nd Input: Any number of integer values (order doesn't matter) that represent the columns that we want to remove. (Look at the data again and find which column contains the non-numeric values). We also want to remove the first column because that only contains the row number, which is irrelevant to our analysis.</li>
    <ul>
        <li> Note: Remember that Python is zero-indexed, therefore the first column would be 0. </li>
    </ul>
</ul>


In [44]:
my_data.columns

Index(['Unnamed: 0', 'epoch', 'mb', 'bh', 'bl', 'nh'], dtype='object')

In [48]:
# Remove the column containing the target name since it doesn't contain numeric values.
# Also remove the column that contains the row number
# axis=1 means we are removing columns instead of rows.
# Function takes in a pandas array and column numbers and returns a numpy array without
# the stated columns


def removeColumns(pandasArray, *column):
    
    # print ([column])
    # print (pandasArray.values)
    
    return pandasArray.drop(pandasArray.columns[[column]], axis=1).values
    
new_data = removeColumns(my_data, 0,1)

print(new_data)

[[131 138  89  49]
 [125 131  92  48]
 [131 132  99  50]
 [119 132  96  44]
 [136 143 100  54]
 [138 137  89  56]
 [139 130 108  48]
 [125 136  93  48]
 [131 134 102  51]
 [134 134  99  51]
 [129 138  95  50]
 [134 121  95  53]
 [126 129 109  51]
 [132 136 100  50]
 [141 140 100  51]
 [131 134  97  54]
 [135 137 103  50]
 [132 133  93  53]
 [139 136  96  50]
 [132 131 101  49]
 [126 133 102  51]
 [135 135 103  47]
 [134 124  93  53]
 [128 134 103  50]
 [130 130 104  49]
 [138 135 100  55]
 [128 132  93  53]
 [127 129 106  48]
 [131 136 114  54]
 [124 138 101  46]
 [124 138 101  48]
 [133 134  97  48]
 [138 134  98  45]
 [148 129 104  51]
 [126 124  95  45]
 [135 136  98  52]
 [132 145 100  54]
 [133 130 102  48]
 [131 134  96  50]
 [133 125  94  46]
 [133 136 103  53]
 [131 139  98  51]
 [131 136  99  56]
 [138 134  98  49]
 [130 136 104  53]
 [131 128  98  45]
 [138 129 107  53]
 [123 131 101  51]
 [130 129 105  47]
 [134 130  93  54]
 [137 136 106  49]
 [126 131 100  48]
 [135 136  9

Now, we have one half of the required data to fit a model, which is X or new_data

Next, we need to get the response vector y. Since we cannot use .target and .target_names, I have created a function that will do this for us.


<b> targetAndtargetNames(numpyArray, targetColumnIndex) </b>

This function produces two outputs, and requires two inputs.
<ul>
    <li> <font size = 3.5><b><i>1st Input</i></b></font>: A numpy array. The numpy array you will use is my_data.values (or my_data.as_matrix())</li>
    <ul>
        <li> Note: DO NOT USE <b> new_data </b> here. We need the original .csv data file without the headers </li>
    </ul>
</ul>
<ul>
    <li> <font size = 3.5><b><i>2nd Input</i></b></font>: An integer value that represents the target column . (Look at the data again and find which column contains the non-numeric values. This is the target column)</li>
    <ul>
        <li> Note: Remember that Python is zero-indexed, therefore the first column would be 0. </li>
   </ul>
</ul>

<ul>
    <li> <font size = 3.5><b><i>1st Output</i></b></font>: The response vector (target) </li>
    <li> <font size = 3.5><b><i>2nd Output</i></b></font>: The target names (target_names) </li>
</ul>



In [55]:
def targetAndtargetNames(numpyArray, targetColumnIndex):
    target_dict = dict()
    target = list()
    target_names = list()
    count = -1
    for i in range(len(my_data.values)):
        if my_data.values[i][targetColumnIndex] not in target_dict:
            count += 1
            target_dict[my_data.values[i][targetColumnIndex]] = count
        target.append(target_dict[my_data.values[i][targetColumnIndex]])
    # Since a dictionary is not ordered, we need to order it and output it to a list so the
    # target names will match the target.
    for targetName in sorted(target_dict, key=target_dict.get):
        target_names.append(targetName)
    return np.asarray(target), target_names

target, target_names = targetAndtargetNames(my_data, 1)

print(target)

print(len(target))

print (my_data.values)

print(target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4]
150
[[1 'c4000BC' 131 138 89 49]
 [2 'c4000BC' 125 131 92 48]
 [3 'c4000BC' 131 132 99 50]
 [4 'c4000BC' 119 132 96 44]
 [5 'c4000BC' 136 143 100 54]
 [6 'c4000BC' 138 137 89 56]
 [7 'c4000BC' 139 130 108 48]
 [8 'c4000BC' 125 136 93 48]
 [9 'c4000BC' 131 134 102 51]
 [10 'c4000BC' 134 134 99 51]
 [11 'c4000BC' 129 138 95 50]
 [12 'c4000BC' 134 121 95 53]
 [13 'c4000BC' 126 129 109 51]
 [14 'c4000BC' 132 136 100 50]
 [15 'c4000BC' 141 140 100 51]
 [16 'c4000BC' 131 134 97 54]
 [17 'c4000BC' 135 137 103 50]
 [18 'c4000BC' 132 133 93 53]
 [19 'c4000BC' 139 136 96 50]
 [20 'c4000BC' 132 131 101 49]
 [21 'c4000BC' 126 133 102 51]
 [22 'c4000BC' 135 135 103 47]
 [23 'c4000BC' 134 124 93 53]

---------
Now that we have the two required variables to fit the data, a sneak peak at how to fit data will be shown in the cell below.

The data will be fit into a K-Nearest Neighbors model, which will be discussed more in a future lab.<br>
<b>Note</b>: The predict function will show a warning when run. Please ignore the warning.

In [62]:
X = new_data

y = target

neigh = KNeighborsClassifier(n_neighbors=1)

neigh.fit(X, y)

print('Prediction:')

print (neigh.predict(new_data))

print('Actual:')

print (y)

Prediction:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4]
Actual:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4]


In [63]:

neigh7 = KNeighborsClassifier(n_neighbors=7)

neigh7.fit(X, y)

print('Prediction:')

print (neigh7.predict(new_data))

print('Actual:')

print (y)

Prediction:
[2 0 0 0 2 3 1 0 0 0 3 4 0 0 0 3 0 1 2 0 0 0 0 0 1 2 0 0 1 0 0 0 2 1 1 1 1
 1 0 1 0 3 1 2 0 1 1 0 1 3 1 0 3 1 0 3 1 0 3 0 2 0 3 0 2 2 2 3 2 0 3 2 2 2
 1 0 1 4 2 4 1 0 2 1 2 4 0 1 2 2 1 3 3 2 3 3 4 2 2 2 3 1 1 3 3 3 1 0 3 3 3
 4 2 0 1 3 3 4 3 1 4 2 0 1 3 0 4 1 3 4 4 0 4 4 2 1 2 4 1 4 2 1 4 0 3 4 1 1
 4 1]
Actual:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4]


Now as you can see above, even though both <b>neigh</b> and <b>neigh7</b> were trained under the <b>same model</b>, by modifying the value of <b>n_neighbors</b> we obtained a <b>different prediction</b> for each.

Therefore it's important to note the different components in an algorithm and understand how they affect your result

### Supervised Learning I

#### K-Nearest Neighbors

KNN is a supervised learning method used for both **Classification and Regression**

- for Classification, the op of KNN is the class of unknown data pt based on KNN of training data

- for Regression, the op is the avg of the values of a target var based on KNN of training data

In Classification, KNN works as follows:

1. Pick a value of K

2. Search for the K observations in the training data that are "nearest" to the measurements of the unknown data

3. Predict the response of the unknown data point using the most popular response value from the K nearest neighbor

** Very low value of K (=1)**

We are trying to classify our data pts into 2 cats - Red and Blue

<img src = "./data/img/diag11" height="500" width = "500" align="center">

The black dotted ine is the curve that separates the blue and red classification regions

We want to use a K that will create a separation of the regions that **best matches this black line**

In this dig there are very jagged edges following the data pts

We have an out-of-sample data pt (pink) 

Its nearest pt(k=1) is blue as thats the pt it is on

This is a bad predn since more of the pts around it is red. So the pt should be considered red

But since we predict it as blue, we can say we have captured the noise in the data, or we have chosen one of the pts that represents an anomaly in the data

See the diag on the right

The division line bw these 2 cats would be very **complex** 

A low K value causes a highly complex model which causes Overfitting of data

Overfitting is bad as we want a general model that works for any data, not just the trained data

** Very high value of K (=100)**

Model becomes overly generalized

This makes it diff to generalie bw 2 regions if a pt appears bw the 2 regs

<img src = "./data/img/diag12" height="500" width = "500" align="center">

White reg is a spot where neither blue or red can be decided

Pink pt: out of sample data pt.But we cant tell which reg it belongs to

If we see the black dotted line that we ideally want to follow, we see that the model does not follow this at all

** Decent value (k=16)**

The divide in the data **mimics the black dotted line **

This produces a fairly accurate model for this dataset

Also there are no areas of noise like in diag with a low k value

Lighter shades simply mean that the model is less confident about the classification

<img src = "./data/img/diag13" height="500" width = "500" align="center">

Looking at the data the line would be something like the one at the right-top

This is far more general than the one before (right-bottom)

** KNN Regression **

<img src = "./data/img/diag14" height="500" width = "500" align="center">

This is used for predicting outcome of ind var given a set of ind vars

A set of uncolored pts are drawn from set of y and x values

These uncolored pts are training data

We want to use KNN to predict y for x=5.6 (query point)

Say k=1

Here we search training set and locate the pt closest to query pt

Here it is x = 6

y(predicted) = y6 (y value for x=6)

So for 1 nearest neighbor y = y6

This point is the red circle in the diag

Say k = 2

We locate first 2 closest pts to x i.e x5 and x6

y = (y5+y6)/2

This is green circle

Alternatively there is the weighted KNN Algo

This assigns weights to the kn nearest neighbors depending on the distance to query pt

Closer the neighboring pt is to the query pt, larger will be the wts

Sum of wts == 1
